[package]
name = "relay-node"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = {version= "0.52.1", features = ["full"]}
tokio = { version = "1.29.1", features = ["full"] }
serde = "1.0.175"
serde_json = "1.0.103"
rand = "0.8.5"
log = "0.4.20"
env_logger = "^0.10"
sp-core = "23.0.0"