[package]
name = "relay-node"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = {version= "^0.52.4", features = ["full"]}
tokio = { version = "1.29.1", features = ["full"] }
serde = "1.0.175"
serde_json = "1.0.103"
rand = "0.8.5"
sp-core = "^24.0"
bip39 = "^2.0"
seed15 = "^0.1"
crossterm = "0.27.0"